### ISSUE TITLE
adding some hovering effects to the images 

### ISSUE THREAD

**Issue by reshamsai150** [MinavKaria/Ratna-Supermarket#1]
![image](https://github.com/user-attachments/assets/3fefb881-9888-491b-a3de-5355a2646d1b)

**Comment by Sureshwebdeveloper** [comment]
@reshamsai150  Please add the gssocext and hactoberfest badges and assign to me

**Comment by Charul00** [comment]
i want to work on this

**Comment by AskitEndo** [comment]
@MinavKaria Can I work on this?

**Comment by MinavKaria** [comment]
Hello @reshamsai150! Your issue #1 has been closed. Thank you for your contribution!🚀

**Comment by MinavKaria** [comment]
Hello @reshamsai150! Your issue #1 has been closed. Thank you for your contribution!🚀
