### ISSUE TITLE
Create Bottom Navbar for Mobile Version

### ISSUE THREAD

**Issue by samar12-rad** [MinavKaria/Ratna-Supermarket#107]
Description:

We need to design and implement a bottom navigation bar for the mobile version of our website. This navbar will mimic the UI of mobile applications that have a bottom navbar, providing users with easy access to key sections of the site.
@MinavKaria 
Requirements:

The navbar should be positioned at the bottom of the mobile screen.

Ensure the navbar is responsive and adapts to different screen sizes.
Follow the existing design language of the desktop navbar to maintain consistency.
Implement any necessary animations for smooth transitions when navigating between sections.
Acceptance Criteria:

The bottom navbar is functional and fully responsive.
Icons and labels are clearly visible and aligned properly.
Users can navigate to all specified sections without issues.
The design is tested on various mobile devices for compatibility.

**Comment by samar12-rad** [comment]
@MinavKaria pls assign me this

**Comment by MinavKaria** [comment]
@samar12-rad you are good to go

**Comment by MinavKaria** [comment]
@samar12-rad any updates for this issue ?

**Comment by samar12-rad** [comment]
I will push it by today sir @MinavKaria

**Comment by Sourabh782** [comment]
> @samar12-rad any updates for this issue ?

@MinavKaria can i work on this issue? i see it unresolved for around 2 weeks now. If its free i would like to work on it :)

**Comment by MinavKaria** [comment]
Hello @samar12-rad! Your issue #107 has been closed. Thank you for your contribution!🚀
