### ISSUE TITLE
Topic: Adding a X symbol to the pincode entering popup

### ISSUE THREAD

**Issue by tarunkumar2005** [MinavKaria/Ratna-Supermarket#108]
### Describe the types of topics you'd add in our Website

As you can see in the image i have already filled the pincode but i clicked again but don't wanna fill it so  i have no option to go back this shouldn't be there. 

@MinavKaria Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Could you share some screenshots or a video of your previous work?

![image](https://github.com/user-attachments/assets/531abd3c-88a4-423b-a891-34f97a910cba)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @tarunkumar2005! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @tarunkumar2005! Your issue #108 has been closed. Thank you for your contribution!🚀
