### ISSUE TITLE
i will make cart section better with images

### ISSUE THREAD

**Issue by Yashwanth-raju005** [MinavKaria/Ratna-Supermarket#109]
i will make cart page better now its not showing total amount and the pics of the items i will add pics and also give the grand total for check out i will enhance the cart page i hope it will be helpful for your website and ux will be more bette than now please assign  me

**Comment by MinavKaria** [comment]
Hi @Yashwanth-raju005! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @Yashwanth-raju005! Your issue #109 has been closed. Thank you for your contribution!🚀
