### ISSUE TITLE
adding a github icon and navigation to the repo

### ISSUE THREAD

**Issue by devxMani** [MinavKaria/Ratna-Supermarket#114]
for the contributors to directly navigate to the repo
add gsoc ext label

**Comment by MinavKaria** [comment]
Hi @devxMani! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @devxMani! Your issue #114 has been closed. Thank you for your contribution!🚀
