### ISSUE TITLE
Add Hover Effect on 'Contact Us'

### ISSUE THREAD

**Issue by ShrutiDesai7** [MinavKaria/Ratna-Supermarket#116]
I would like to suggest adding a CSS hover effect to the "Contact Us" .

https://github.com/user-attachments/assets/b6e4f296-ce75-4905-8a6d-7e882e12f71e

If this suggestion sounds good, I’d be happy to work on it.

**Comment by MinavKaria** [comment]
Hi @ShrutiDesai7! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by ShrutiDesai7** [comment]
Please assign this to me.

**Comment by MinavKaria** [comment]
Hello @ShrutiDesai7! Your issue #116 has been closed. Thank you for your contribution!🚀
