### ISSUE TITLE
fix issue of login and signup form ui

### ISSUE THREAD

**Issue by shivamy009** [MinavKaria/Ratna-Supermarket#12]
![Screenshot 2024-10-02 073542](https://github.com/user-attachments/assets/50652afc-3ffc-41d7-bdbd-d39b56cdae05)
![Screenshot 2024-10-02 073534](https://github.com/user-attachments/assets/a282f8cb-4df4-4de7-9901-5521d832abac)
herer i think ui of got exchanged

**Comment by MinavKaria** [comment]
Do you want to fix it ?

**Comment by saurabh007007** [comment]
can you assign me this issue

**Comment by MihirSaiDudekula** [comment]
@MinavKaria can you assign it to me?

**Comment by AskitEndo** [comment]
@MinavKaria Worked on it and fixed it , Do review and merger Accordingly
