### ISSUE TITLE
Chat Bot

### ISSUE THREAD

**Issue by 2004shweta** [MinavKaria/Ratna-Supermarket#126]
Add personal chat bot to website. which will enhance the user experience.

**Comment by MinavKaria** [comment]
Hi @2004shweta! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by GirishaMalni** [comment]
Hello, I would like to contribute to this

**Comment by GirishaMalni** [comment]
Please include me in this repository as I am new to open source contribution

**Comment by MinavKaria** [comment]
This is already raised by another contributor, so please comment on that so that I can assign you there. @GirishaMalni

**Comment by MinavKaria** [comment]
Hello @2004shweta! Your issue #126 has been closed. Thank you for your contribution!🚀
