### ISSUE TITLE
Problem in heading in mobile view

### ISSUE THREAD

**Issue by krishpathak** [MinavKaria/Ratna-Supermarket#136]
### Describe the types of topics you'd add in our Website

![image](https://github.com/user-attachments/assets/93459ed8-b2d8-4680-989b-6587dff42079)
Here, explore more products that are not properly visible on mobile.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hello @krishpathak! Your issue #136 has been closed. Thank you for your contribution!🚀
