### ISSUE TITLE
Topic: Adding a chatbot / help icon 

### ISSUE THREAD

**Issue by aarushsaboo** [MinavKaria/Ratna-Supermarket#139]
### Describe the types of topics you'd add in our Website

I wanna add a chatbot icon at the bottom right corner of the page which will perform the functions of a standard chatbot designated to answer any queries about the products, etc.
Clicking it will open a small chatbot wherein customers can write and post any queries.
Pls assign it to me under the label of hacktober-fest. Tnx

### Could you share some screenshots or a video of your previous work?

![image](https://github.com/user-attachments/assets/63e27750-3039-466c-93ef-2bb14ad087f7)
![image](https://github.com/user-attachments/assets/4180ee71-237c-4bd4-9e2e-450fe0f5e3d2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @aarushsaboo! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by raj-adi00** [comment]
Can you please assign this issue to me

**Comment by MinavKaria** [comment]
Hello @aarushsaboo! Your issue #139 has been closed. Thank you for your contribution!🚀
