### ISSUE TITLE
Topic: [FEATURE] adding gssoc-ext and hacktober fest logos to the readme

### ISSUE THREAD

**Issue by REHAN-18** [MinavKaria/Ratna-Supermarket#144]
### Describe the types of topics you'd add in our Website

adding gssoc-ext and hacktober fest logos to the readme will enhance the repo update the readme file 

### Could you share some screenshots or a video of your previous work?

<img width="989" alt="Screenshot 2024-10-18 at 11 57 18 PM" src="https://github.com/user-attachments/assets/6995f85e-af2f-4117-b0f3-eea3b48c002d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @REHAN-18! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
@REHAN-18 GSSOC Logo is already added

**Comment by MinavKaria** [comment]
Hello @REHAN-18! Your issue #144 has been closed. Thank you for your contribution!🚀
