### ISSUE TITLE
Improvement in simpleDialog box component

### ISSUE THREAD

**Issue by Muralidhar216** [MinavKaria/Ratna-Supermarket#156]
![image](https://github.com/user-attachments/assets/c65c6c66-8b38-4948-883e-0c787a0147bf)
It will be improvise similar to it

**Comment by MinavKaria** [comment]
Hi @Muralidhar216! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @Muralidhar216! Your issue #156 has been closed. Thank you for your contribution!🚀
