### ISSUE TITLE
Topic:Add blog page

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [MinavKaria/Ratna-Supermarket#159]
### Describe the types of topics you'd add in our Website

Add blog page

### Could you share some screenshots or a video of your previous work?

Add blog page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @KapuluruBhuvaneswariVspdbct! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @KapuluruBhuvaneswariVspdbct! Your issue #159 has been closed. Thank you for your contribution!🚀
