### ISSUE TITLE
Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [MinavKaria/Ratna-Supermarket#163]
Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

**Comment by RNAdvani** [comment]
@MinavKaria i would like to work on this can you assign this to me

**Comment by MinavKaria** [comment]
Hello @TBorundia! Your issue #163 has been closed. Thank you for your contribution!🚀
