### ISSUE TITLE
Pincode input gets stuck if re-entry is canceled after initial entry

### ISSUE THREAD

**Issue by namansinghrana** [MinavKaria/Ratna-Supermarket#189]
### Steps to reproduce bug : 
1. Go to the home page.
2. Enter a valid pincode and wait for the confirmation.
3. Try to edit the pincode by selecting the field again.
4. Click the "Cancel" button or outside the field without re-entering a new pincode.
5. Observe that the pincode field prompts for input again instead of using the last entered pincode.

### Expected Behaviour :
When canceling the pincode re-entry, the field should retain the previously entered pincode instead of requesting input again.

### Actual Behavior :
The field prompts for the pincode again, disregarding the previously entered pincode, and prevents the user from proceeding without re-entering it.

### Screenshot : 
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/fb175995-ad35-45c0-bb2f-f141b22db389">

**Comment by MinavKaria** [comment]
Hi @namansinghrana! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @namansinghrana! Your issue #189 has been closed. Thank you for your contribution!🚀
