### ISSUE TITLE
Topic: ✨ Feature Request

### ISSUE THREAD

**Issue by subodhkangale07** [MinavKaria/Ratna-Supermarket#190]
### Describe the types of topics you'd add in our Website

Enhanced the CSS styling for the footer and cart components to improve visual appeal and user experience, ensuring better layout alignment, consistent design, and responsiveness across different screen sizes.

### Could you share some screenshots or a video of your previous work?

Before:
![image](https://github.com/user-attachments/assets/161be013-9ab5-4990-9917-5108132d9b64)

CART

Before:

![image](https://github.com/user-attachments/assets/d6560854-8a4b-44c1-9306-b486fa4ee425)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I have read other issues and did not find a similar or same issue. Ensuring that, this is a new issue

**Comment by MinavKaria** [comment]
Hi @subodhkangale07! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by subodhkangale07** [comment]
/aasign kindly assign this issue to me

**Comment by MinavKaria** [comment]
Hello @subodhkangale07! Your issue #190 has been closed. Thank you for your contribution!🚀
