### ISSUE TITLE
Generate Sitemap.xml and Robots.txt to improve SEO and Site Crawling

### ISSUE THREAD

**Issue by amiya-cyber** [MinavKaria/Ratna-Supermarket#193]
Adding sitemap.xml and robots.txt files helps optimize a website for search engines.

Sitemap.xml provides a list of important URLs, helping search engines discover, crawl, and index new and updated content faster, improving SEO.

Robots.txt controls which parts of the site search engines can access, preventing indexing of sensitive or unimportant pages, conserving crawl budget, and reducing server load.

Together, they enhance site visibility, performance, and search engine ranking.

ASSIGN WITH LEVEL 2 OR LEVEL 3

**Comment by MinavKaria** [comment]
Hi @amiya-cyber! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @amiya-cyber! Your issue #193 has been closed. Thank you for your contribution!🚀
