### ISSUE TITLE
Adding and deleting item 

### ISSUE THREAD

**Issue by VJ12More** [MinavKaria/Ratna-Supermarket#196]
When we add the item to our cart the "+" sign to add 2nd item should  be on right side and  to delete the item "-" sign should be on left
 hand side . 
![Screenshot 2024-11-08 113238](https://github.com/user-attachments/assets/722c5b82-2675-4a8a-8384-415c576131b2)

**Comment by MinavKaria** [comment]
Hi @VJ12More! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by VJ12More** [comment]
Assign this task to me .

**Comment by MinavKaria** [comment]
@VJ12More  Check the current version link on the repo

**Comment by MinavKaria** [comment]
Hello @VJ12More! Your issue #196 has been closed. Thank you for your contribution!🚀
