### ISSUE TITLE
Make it responsive for mobile devices

### ISSUE THREAD

**Issue by R1MO9** [MinavKaria/Ratna-Supermarket#201]
### Describe the types of topics you'd add in our Website

The product details page isn't responsive at all for mobile screen
![image](https://github.com/user-attachments/assets/50d40cb1-a555-4f7e-8ee0-80ab7527dfd0)

please assign this to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I have read other issues and did not find a similar or same issue. Ensuring that, this is a new issue

**Comment by MinavKaria** [comment]
Hi @R1MO9! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by R1MO9** [comment]
@MinavKaria what is the update?

**Comment by MinavKaria** [comment]
@R1MO9 Check the new deployed version

**Comment by MinavKaria** [comment]
Hello @R1MO9! Your issue #201 has been closed. Thank you for your contribution!🚀
