### ISSUE TITLE
There are variations in color consistency

### ISSUE THREAD

**Issue by divyanshudhruv** [MinavKaria/Ratna-Supermarket#203]
**The image uses green and orange together, but having both colors on the website might look out of place. This mix creates inconsistency and disrupts the overall balance of the existing green and yellow color scheme.**

<img src="https://github.com/user-attachments/assets/6198815a-10c7-4585-a33d-c58aed717726" width="200">

**Comment by MinavKaria** [comment]
Hi @divyanshudhruv! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by divyanshudhruv** [comment]
Hi, Have you seen the issue?

**Comment by MinavKaria** [comment]
@divyanshudhruv Hey Contributor , Thank you for pointing out this issue. This issue is too small to be assigned, as we need to just change 1 line of code here. If you have any other issue , I can assign you this along with that.

**Comment by divyanshudhruv** [comment]
Sure, I will look for any more changes and reply you back soon.
