### ISSUE TITLE
Adding Hyperlink to email id in footer 

### ISSUE THREAD

**Issue by nksmanya** [MinavKaria/Ratna-Supermarket#21]
I would like to add a hyperlink to the email ID (support@ratna.in), to open an email when the email ID is clicked directly. 

@MinavKaria I kindly request you to assign this issue to me. 
Also please add the corresponding labels.

**Comment by MinavKaria** [comment]
Hi @nksmanya! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
