### ISSUE TITLE
Updating the twitter logo

### ISSUE THREAD

**Issue by nksmanya** [MinavKaria/Ratna-Supermarket#22]
@MinavKaria  I would like to update the old twitter logo to the new X logo. 
Please assign this issue to me. 
Also, I request you to mark the corresponding labels to this issue.

**Comment by MinavKaria** [comment]
You are good to go

**Comment by nksmanya** [comment]
@MinavKaria I have updated the twitter logo. 
This is the first time I am doing an open source and I am not sure if I did the pull request correctly.
Please let me know if there is any issue.

**Comment by nksmanya** [comment]
@MinavKaria My contribution towards this issue does not get counted towards the leaderboard. 
Can you please help me with this ?

**Comment by MinavKaria** [comment]
Hello @nksmanya! Your issue #22 has been closed. Thank you for your contribution!🚀

**Comment by MinavKaria** [comment]
It should mostly, check in one day
