### ISSUE TITLE
Standard ReadMe,Contribution,Code of conduct missing.

### ISSUE THREAD

**Issue by AskitEndo** [MinavKaria/Ratna-Supermarket#23]
Readme Not Updated Properly, and CONTRIBUTING.md Missing
Also no CODE OF CONDUCT.

All have to be Written to maek the Project comapatible with **HACKTOBER-FEST** and **GSSOC** properly

**Comment by MinavKaria** [comment]
Hi @AskitEndo! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by AskitEndo** [comment]
@MinavKaria Do Assign me the Issue as the Fix has been Implemented Review and merge accordingly 🫶🏻
