### ISSUE TITLE
MongoDB connection string exposed in backend.py

### ISSUE THREAD

**Issue by MihirSaiDudekula** [MinavKaria/Ratna-Supermarket#27]
Use environment variables for safety.
Kindly assign me this issue.

**Comment by MinavKaria** [comment]
Hi @MihirSaiDudekula! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by Charul00** [comment]
can i work on this please assign me

**Comment by MinavKaria** [comment]
In which file is it exposed ?

**Comment by MihirSaiDudekula** [comment]
here, backend.py

![image](https://github.com/user-attachments/assets/c0db3e6c-0aaf-43fb-aff0-a5cb43258783)

**Comment by MinavKaria** [comment]
Thx for informing I'll change the env by changing the username password. Actually, python backend here is not in use

**Comment by MinavKaria** [comment]
Only Nodejs is working here

**Comment by MihirSaiDudekula** [comment]
Ohk,
My bad, got confused.
