### ISSUE TITLE
Topic:Task Request for Improving Mobile Responsiveness

### ISSUE THREAD

**Issue by krishpathak** [MinavKaria/Ratna-Supermarket#33]
### Describe the types of topics you'd add in our Website

Hi @MinavKaria,

Please find the attached screenshots. The single product page looks great on desktop, but it doesn’t fit properly on mobile view. I’d like to fix this and enhance its responsiveness.

Here are the attachments for your reference:

1. Current mobile view
2.  Proposed fixed UI for responsiveness
Could you please assign me this task?

Thank you!

1. ![Screenshot 2024-10-03 113003](https://github.com/user-attachments/assets/0d56c265-8d98-41b7-ac3d-278e381cc364)
2. ![Screenshot 2024-10-03 112445](https://github.com/user-attachments/assets/379f1318-cf98-47d9-bca3-e18fcb77f37e)

### Could you share some screenshots or a video of your previous work?

I’ve worked on several projects and focused on making them responsive. Attached is a screenshot of one of the projects for your reference.

Please let me know if you need any more details!

Mobile view:
![image](https://github.com/user-attachments/assets/9fabfc33-ac8e-4ac0-9837-f85e28df6c9b)

Desktop view:
![image](https://github.com/user-attachments/assets/687797e1-8bc3-47ac-bc60-dedd86e1fcc7)

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [x] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @krishpathak! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by krishpathak** [comment]
@MinavKaria I hope you will look into this issue and kindly assign me to fix this ,with a GSSOC-ext and HackoctoberFest label . Thanks in anticipation!! And looking for your response.

**Comment by MinavKaria** [comment]
You are good to go
