### ISSUE TITLE
[Enhancement] Make cursor pointer while hovering over products

### ISSUE THREAD

**Issue by muhafiz5814** [MinavKaria/Ratna-Supermarket#34]
**Description** 
Cursor is not changing to pointer and being default while hovering over the products and categories.
It is a bad user experience as user will not understand if these are clickable or not.

**Screenshot**
![Screenshot (1637)](https://github.com/user-attachments/assets/1e872e42-ff47-4634-8772-7b6e3bc2663e)

I would like to get assigned this issue so that I can work on it as soon as possible.

**Comment by MinavKaria** [comment]
Hi @muhafiz5814! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by muhafiz5814** [comment]
Hi @MinavKaria! I will be waiting for your response.
