### ISSUE TITLE
Topic: The payment box overflows into nav bar upon scrolling

### ISSUE THREAD

**Issue by ZayedShahcode** [MinavKaria/Ratna-Supermarket#36]
### Describe the types of topics you'd add in our Website

So while checking out, when we scroll down the payment box gets super imposed on navbar. I want ot fix this issue.
![image](https://github.com/user-attachments/assets/cde4c841-6d16-48bc-a560-c195a3dce8da)

Please assign this issue to me under gssoc extd and hacktoberfest

### Could you share some screenshots or a video of your previous work?

I have previously worked on many full stack websites. Here are few screen shots of my latest work.

![image](https://github.com/user-attachments/assets/fdb16f84-e24b-4385-a90d-60082e85f12d)

![image](https://github.com/user-attachments/assets/a4bda573-a499-4049-bf0d-401896a4a723)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Ok I'll assign you ,before that I wanted to ask Why is the Navbar looking different in your image from normal ?

**Comment by ZayedShahcode** [comment]
I don't know, I just opened the website on my local server and logged in using my google account. It was just like that. I can fix that too, if you would like.

**Comment by MinavKaria** [comment]
Hello @ZayedShahcode! Your issue #36 has been closed. Thank you for your contribution!🚀
