### ISSUE TITLE
Dockerize the App

### ISSUE THREAD

**Issue by MinavKaria** [MinavKaria/Ratna-Supermarket#39]
We want this app to be dockerized so it can be deployed as a container if needed, if any wants to do this feel free to comment down below.

**Comment by MinavKaria** [comment]
Hi @MinavKaria! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by pushkardev123** [comment]
assign this to me please

**Comment by pushkardev123** [comment]
please assign this to someone else, im unable to complete this task as of now.

**Comment by MinavKaria** [comment]
If anyone else wants to contribute on this, feel free to comment down below

**Comment by LaibaKhalil61** [comment]
@MinavKaria assign this to me

**Comment by Mahateaa** [comment]
Heyyyy can you assign me this task??

**Comment by MinavKaria** [comment]
Whom should I assign @LaibaKhalil61 @Mahateaa @space-techy ?? The person to reply first will get assigned

**Comment by space-techy** [comment]
Me

**Comment by space-techy** [comment]
@MinavKaria  Done with making Docker Compose file!
Ready to launch the pull request!

**Comment by space-techy** [comment]
Created Pull Request Please check

**Comment by MinavKaria** [comment]
Hello @MinavKaria! Your issue #39 has been closed. Thank you for your contribution!🚀
