### ISSUE TITLE
Adding links to the facebook,insta,twitter etc. images

### ISSUE THREAD

**Issue by ShreyaSnehal** [MinavKaria/Ratna-Supermarket#4]
![image](https://github.com/user-attachments/assets/fbfab6e7-3919-4cc2-8e0f-c2738b24f2e7)

**Comment by Sureshwebdeveloper** [comment]
@reshamsai150  Please add the gssocext and hactoberfest badges and assign to me

**Comment by MinavKaria** [comment]
Not needed, If you want to change something else, you are free to open a new issue.
