### ISSUE TITLE
Add Scroll to top button 

### ISSUE THREAD

**Issue by shubhagarwal1** [MinavKaria/Ratna-Supermarket#47]
Websites, currently do not have a scroll to top button which can we time taking for user when number of blogs increases on the page, i will add a scroll to top button on blogs page and dedicated blog page for improving user experiece as when number of product will increse  on the site
Hey @MinavKaria  please assign this task to me

**Comment by MinavKaria** [comment]
Hi @shubhagarwal1! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @shubhagarwal1! Your issue #47 has been closed. Thank you for your contribution!🚀
