### ISSUE TITLE
City Name Overflow in Navbar

### ISSUE THREAD

**Issue by c2gup** [MinavKaria/Ratna-Supermarket#5]
When the name of a city is too long, it overflows the content area of the navbar, affecting the overall layout. This causes the city name to extend beyond its container, disrupting the design.

i want to solve these issue please assign me this

here is the image of the overflow issue 
![Uploading Screenshot (183).png…]()

**Comment by MinavKaria** [comment]
Hello @c2gup! Your issue #5 has been closed. Thank you for your contribution!🚀
