### ISSUE TITLE
[BUG]: The social media buttons are not working  

### ISSUE THREAD

**Issue by ArthKulkarni93** [MinavKaria/Ratna-Supermarket#51]
**Describe the types of topics you'd add in our Website**

1. When we click on the social media icons nothing happens, no function is triggered.
2. Most of the contents are getting logged in console, this can lead to 1)Security vulnerabilities 2)Maintenance Challenges 3)Bad 
User Experience

https://github.com/user-attachments/assets/55bb865b-5479-4fdb-ab81-5dc8271b1aa4

**Record**

- [ ✅]  I agree to follow this project's Code of Conduct
- [✅ ]  I'm a GSSOC-24-extd contributor
- [ ✅]  Soon, I'll complete it and create a Pull Request.

Please assign this issue to me and get it done today itself

**Comment by MinavKaria** [comment]
Hi @ArthKulkarni93! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @ArthKulkarni93! Your issue #51 has been closed. Thank you for your contribution!🚀
