### ISSUE TITLE
Improve a footer 

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [MinavKaria/Ratna-Supermarket#52]
![image](https://github.com/user-attachments/assets/a8fbc7b1-715b-4981-a349-fc4365d28993) 

Improve footer needed cause other ecommerce web page have easy navigation attractive colors easy user navigation responsive design as well assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as well

**Comment by MinavKaria** [comment]
Hi @Sureshwebdeveloper! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @Sureshwebdeveloper! Your issue #52 has been closed. Thank you for your contribution!🚀
