### ISSUE TITLE
Need a improvement for shoppingcart page user increase or decrease a product and display a user order items image

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [MinavKaria/Ratna-Supermarket#53]
![image](https://github.com/user-attachments/assets/cd151f5e-710a-48a4-838c-7b207ba7a9f5)

improvements needed for shopping cart page user need to increase or decrease a products and better ui and  need to display a user cart items image  example if user order  Rich Eggs we need to display a Rich Eggs image 
If you assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as well

**Comment by Sureshwebdeveloper** [comment]
Sure I will Work On That Thanks For Assign to Me 🙂

**Comment by MinavKaria** [comment]
Hello @Sureshwebdeveloper! Your issue #53 has been closed. Thank you for your contribution!🚀
