### ISSUE TITLE
Email and Phone app when click on contact us email and phone 

### ISSUE THREAD

**Issue by 17arindam** [MinavKaria/Ratna-Supermarket#54]
### Describe the types of topics you'd add in our Website

-redirect to email app when user clicks on contact us email
-redirect to phone app when user clicks on contact us phone

### Could you share some screenshots or a video of your previous work?

![image](https://github.com/user-attachments/assets/5a69bee8-d46f-470f-a5fd-871cae497c42)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @17arindam! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @17arindam! Your issue #54 has been closed. Thank you for your contribution!🚀
