### ISSUE TITLE
Feat: Add Hover Effect on Product Categories

### ISSUE THREAD

**Issue by HarshadaGirase** [MinavKaria/Ratna-Supermarket#56]
Description:
Adding a hover effect to the product categories on the homepage and relevant category pages. The hover effect will provide a visual indication to users when they hover over a category, enhancing the overall user experience by making the UI more interactive and engaging.

Expected Behavior:

When a user hovers over a product category, the category card will display a subtle animation (e.g., scale, color change, border highlight).
The hover effect should be smooth and responsive, without delaying page load or interaction.
Maintain accessibility considerations by ensuring that the effect is not too distracting and works well with screen readers.

![Uploading hovereffect.png…]()

**Comment by MinavKaria** [comment]
Hi @HarshadaGirase! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by MinavKaria** [comment]
Hello @HarshadaGirase! Your issue #56 has been closed. Thank you for your contribution!🚀
