### ISSUE TITLE
Feat: Create a Separate "Product" Page

### ISSUE THREAD

**Issue by HarshadaGirase** [MinavKaria/Ratna-Supermarket#58]
Description:
 Creating a dedicated "Products" page where customers can browse the entire range of products offered by Ratna Supermarket. This page will improve user navigation, helping customers easily explore product categories and individual items.

Objective:
1. Provide a streamlined and centralized location for all products available in the supermarket.
2. Enhance user experience by enabling easy browsing, filtering, and searching for products.
3. Improve product visibility, leading to better customer engagement and higher sales.

Expected Behavior:

1. Users can access the "Products" page from the main navigation menu or relevant sections of the website.
2. Clicking on a product will lead to a detailed product page with more information 
3. The page will be fully responsive and load efficiently on all devices.

**Comment by MinavKaria** [comment]
Hello @HarshadaGirase! Your issue #58 has been closed. Thank you for your contribution!🚀
