### ISSUE TITLE
Feat:  Add Password Visibility toggle on Sign-Up Page

### ISSUE THREAD

**Issue by HarshadaGirase** [MinavKaria/Ratna-Supermarket#59]
Description:
Adding a "Password Visibility" toggle on the sign-up page to allow users to view or hide their entered password. This feature will improve user experience by reducing errors when entering complex passwords and ensuring that users can verify their input before submission.

Objective:

Enhance usability by allowing users to toggle between hidden and visible password fields.
Reduce errors due to mistyped passwords during the sign-up process.

Expected Behavior:

Users can toggle between showing and hiding the password by clicking on an eye icon next to the password input field.
The password visibility toggle will work in real-time without refreshing the page.
By default, the password will be hidden, but users can click the icon to reveal or hide it as needed.

![pwdtoggle](https://github.com/user-attachments/assets/67f0f955-ca5d-48b3-a8e7-155e297229d0)

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by SuyashSingh01** [comment]
I am interested in contributing to this project as  I came across the issue titled "Feat: Add Password Visibility Toggle on Sign-Up Page" and would love to work on it.

To implement this feature, I propose adding an eye icon to the password input field on the sign-up page, allowing users to toggle between showing and hiding their password. This enhancement will significantly improve user experience by making it easier for users to verify their password entries during registration.

Here's how I plan to proceed:

Add an eye icon button next to the password input field.
Implement JavaScript to toggle the input type between "password" and "text" based on user interaction with the eye icon.
Ensure the UI design remains consistent with the overall application style.
If this solution aligns with your expectations, I would be happy to start working on it. Please let me know if there are any additional requirements or suggestions you have for implementing this feature.


![Screenshot 2024-03-21 111203](https://github.com/user-attachments/assets/3f73995a-c006-454f-9709-49849961bef2)


 I am looking forward to your response and excited to contribute to this project.
