### ISSUE TITLE
Better UI for Signup and Login Pages

### ISSUE THREAD

**Issue by Akshithsaai** [MinavKaria/Ratna-Supermarket#6]
### Issues

1. The UI for Signup and Login is not very handy for the user and likely to be frustrated to fill it up.

### Expected Outcome

1. The Signup and Login Page are horizontally Flipped and UI is made perfectly aligned and visually good.

Assign me this issue @MinavKaria 

Tags: gssoc'24 extd , hacktoberfest'24

**Comment by MinavKaria** [comment]
Ok assign this to you @Akshithsaai
