### ISSUE TITLE
Feat: Display Username After User Login

### ISSUE THREAD

**Issue by HarshadaGirase** [MinavKaria/Ratna-Supermarket#60]
Description:
Displaying the logged-in user's username in the navigation bar or a dedicated section after successful login. This feature will help users identify their active session and provide a more personalized experience on the platform.

Objective:
Display the logged-in user's username prominently on the website to personalize their experience.
Improve user interaction by providing a clear indication that they are logged in.

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by MinavKaria** [comment]
![image](https://github.com/user-attachments/assets/87b0f694-afd4-430f-867f-b49630e141d3)

The user's name is already visible what do you want to interpret ?

**Comment by HarshadaGirase** [comment]
I raised the issues using the deployed link.

**Comment by HarshadaGirase** [comment]
couldn't see latest changes

**Comment by MinavKaria** [comment]
Maybe you didn't login, this feature was available in the previous version as well

**Comment by MinavKaria** [comment]
Hello @HarshadaGirase! Your issue #60 has been closed. Thank you for your contribution!🚀
