### ISSUE TITLE
BUG: "Sign Up" Button Not Functional, Preventing Login

### ISSUE THREAD

**Issue by HarshadaGirase** [MinavKaria/Ratna-Supermarket#61]
Description:
When clicking the "Sign Up" button on the sign-up page, users are unable to proceed. The button is unresponsive, and as a result, users cannot complete the sign-up process or log in. 

Steps to Reproduce:

1. Navigate to the Login Page
2. Click on "Already have an account" link
3. Fill out all required fields (e.g., username, password, etc.).
4. Click the "Sign Up" button.
5. Observe that the button does not trigger any action, and the user remains on the sign-up page without any feedback.

Expected Behavior:

1. After filling in all required fields and clicking the "Sign Up" button, the user should be able to successfully sign up and be redirected to the homepage or a welcome page, where they can log in.
2. The system should display an error message if any required fields are missing or filled incorrectly.

![signup](https://github.com/user-attachments/assets/9436c907-93c8-456f-b42c-26a81bca9707)

**Comment by MinavKaria** [comment]
Currently only google login is working , some other contributor is working on this issue to fix the login and register button. Please check other issues before sending the issue. If you feel to contribute in some other issue please feel free to do so.
