### ISSUE TITLE
BUG: Incorrect Labeling of "Sign Up" and "Sign In" Buttons

### ISSUE THREAD

**Issue by HarshadaGirase** [MinavKaria/Ratna-Supermarket#62]
Description:
The labels for the "Sign Up" and "Sign In" buttons have been incorrectly assigned, leading to confusion regarding their intended functionality. The "Sign Up" button should indicate account creation, while the "Sign In" button should allow users to log in to an existing account. The current labeling does not accurately reflect these functions.

Steps to Reproduce:

1. Navigate to the Login page of the Ratna Supermarket website.
2. Observe the labels on the buttons for signing up and signing in.
3. Note any incorrect wording present on the buttons.

Expected Behavior:
1. The "Sign Up" button should clearly indicate that it is for creating a new account.
2. The "Sign In" button should clearly indicate that it is for logging into an existing account.

![createaccount](https://github.com/user-attachments/assets/36d06df1-4087-41d7-8029-d284e16c4ea6)
![signup](https://github.com/user-attachments/assets/14a4a727-0e03-410a-9cc8-7d0b0351d94f)

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by MinavKaria** [comment]
Hello @HarshadaGirase , This is already fixed in some other issue,

https://ratna-supermaket.minavkaria.xyz/

Check this out here.

**Comment by HarshadaGirase** [comment]
Okay
