### ISSUE TITLE
Make the Navbar Properly Responsive and Add Navbar for Mobile

### ISSUE THREAD

**Issue by MinavKaria** [MinavKaria/Ratna-Supermarket#63]
Width greater than 1550
![image](https://github.com/user-attachments/assets/60d74ac8-0714-4e4b-a1fa-3aa073c7f215)

1549 to 1280
![image](https://github.com/user-attachments/assets/56e741f3-f900-4baa-9f99-a770875d854e)

1280 to 1020
![image](https://github.com/user-attachments/assets/ff02e506-68bd-48b4-b808-da3f408df8e0)

1020 to 768 
![image](https://github.com/user-attachments/assets/f36f8f1a-e6c5-4ec0-b1b6-05a2b5dc01b5)

768 and below
![image](https://github.com/user-attachments/assets/adf3b908-a0e0-4799-81cb-f14c58557433)

As We can see the navbar is breaking apart we need to fix this for PC from 1550 px to 1020 px for PC

For mobile we need navbar like 
![image](https://github.com/user-attachments/assets/2356276b-bea2-4a08-92cf-a53a1ae7d447)

If anyone wants to contribute to this feel free to comment down below.

**Comment by MinavKaria** [comment]
Another idea for Mobile Navbar 
![image](https://github.com/user-attachments/assets/bdf467a7-aec7-46cb-a846-09a476871677)

**Comment by samar12-rad** [comment]
I can solve all the responsiveness problem you mentioned and create a navbar for you . 
I will also create this navbar for the mobile end for starters.
![image](https://github.com/user-attachments/assets/a9e9c2b5-4eb1-404c-bae7-3ae07206ea1c)
pls assign me this issue @MinavKaria

**Comment by MinavKaria** [comment]
You are good to go. I hope you meet the expectation. @samar12-rad

**Comment by MinavKaria** [comment]
@samar12-rad Please give the colors according to the color scheme of the current app

**Comment by samar12-rad** [comment]
@MinavKaria Sure

**Comment by samar12-rad** [comment]
@MinavKaria, You suggested to change responsive till 1020px, but i have to change till 756 px before the mobile view start as it is very important too do that too.

The current implementation of navbar has a lot of nested elements and classes that make it difficult to follow the structure and styling. This complexity can lead to confusion when trying to modify or debug the code, as it's not immediately clear how the different parts are related.

Additionally, the use of various utility classes in a single element makes it hard to see the overall styling intent at a glance. This could hinder our ability to efficiently manage the navbar in the long run.

**Comment by samar12-rad** [comment]
Furthermore, i found the reason of that, the issue is no availability of code reviever like eslint for that, i would like to suggest that i found that through my eslint extension. 

A website of such scale should have libraries like eslint running in them to check problems like these during developement and commits.

**Comment by samar12-rad** [comment]
![image](https://github.com/user-attachments/assets/b653ef98-a726-48ba-ab22-df20c151e65d)
Nabar. jsx has atleast 30-40 unused imports and variables.

**Comment by samar12-rad** [comment]
Can i add Eslint to the project and remove all the errors present in the project, to prevent from future problems like these ?

I will add Eslint to the project, which doesnt let you commit unless you remove unimportant vars .
I will take of whole Eslint errors in the code and clean the code for  you .

**Comment by samar12-rad** [comment]
@MinavKaria

**Comment by MinavKaria** [comment]
Ok @samar12-rad

**Comment by samar12-rad** [comment]
#74 created @MinavKaria 

> Ok @samar12-rad

**Comment by MinavKaria** [comment]
Hello @MinavKaria! Your issue #63 has been closed. Thank you for your contribution!🚀
