### ISSUE TITLE
Topic: Outdated Readme and Documentation

### ISSUE THREAD

**Issue by AskitEndo** [MinavKaria/Ratna-Supermarket#65]
## README Update and Enhancements

The **current README** is **outdated** and no longer aligns with the recent changes and updates made to the project. Many of the **instructions** are now **non-functional** due to the project's evolving structure. Additionally, some **technologies** used in the project are **missing** from the README.

### Required Changes:
1. **Revise the README** to reflect the **latest updates** in the codebase.
2. Ensure all **instructions** are up-to-date and provide clear, working guidance for setting up and running the project.
3. Add a section for **technologies used**, detailing the tools and frameworks integrated into the project.
4. Include some **better animations** or **visual elements** to enhance the overall appeal of the README.
5. **Fetch contributors dynamically**, displaying real-time information about those involved in the project.
6. Add **data statistics** like project metrics and **CONTRIBUTOR GRAPHS** to offer a more insightful view of the project's progress.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by AskitEndo** [comment]
@MinavKaria Look onto it and do Assign me ^_~

**Comment by MinavKaria** [comment]
Ok do it, Make the size of Contributor Logos also proper

**Comment by AskitEndo** [comment]
@MinavKaria Yep, On it..

**Comment by MinavKaria** [comment]
@AskitEndo Can this be done asap

**Comment by AskitEndo** [comment]
> @AskitEndo Can this be done asap

Done

**Comment by MinavKaria** [comment]
Hello @AskitEndo! Your issue #65 has been closed. Thank you for your contribution!🚀
