### ISSUE TITLE
No option for closing Pincode Dialog

### ISSUE THREAD

**Issue by mohit-2003** [MinavKaria/Ratna-Supermarket#66]
There is no option to close the `pincode dialog` box, it shows a warning **`Please enter a valid pincode & select an area from the list.`**.

I would like to contribute by fixing this issue as part of my GSSoC Extd and Hacktoberfest participation. Please assign it to me.

**Comment by MinavKaria** [comment]
Hi @mohit-2003! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @mohit-2003! Your issue #66 has been closed. Thank you for your contribution!🚀
