### ISSUE TITLE
feat : Adding toast messages instead of simple alert box for login signup and pincode checker

### ISSUE THREAD

**Issue by laxmanp090404** [MinavKaria/Ratna-Supermarket#67]
This feature request proposes replacing the current use of simple `alert` boxes with **toast messages** for better user experience and interface design during login, signup, and pincode checker operations.

#### Proposed Changes:
- **Login & Signup**:
  - Replace current `alert` boxes that show success or error messages (e.g., login successful, invalid credentials, etc.) with non-intrusive, visually appealing toast notifications.
- **Pincode Checker**:
  - Display toast messages to show whether the entered pincode is valid or invalid, improving feedback to the user.
  
#### Benefits:
- **Improved UX**: Toast messages provide a cleaner, more modern look than alert boxes, which are disruptive and block user interaction until dismissed.
- **Non-intrusive notifications**: Toasts allow users to continue interacting with the page without interruptions.
- **Customization**: Toast messages can be styled with colors and icons to clearly distinguish between success, error, or information states.

#### Acceptance Criteria:
- All alert boxes in the login, signup, and pincode checker processes should be replaced with toast notifications.
- Toasts should auto-dismiss after a few seconds and should be accessible and responsive.

This enhancement will significantly improve the user experience by making the feedback process smoother and more visually appealing.

**Comment by MinavKaria** [comment]
Hi @laxmanp090404! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by laxmanp090404** [comment]
@MinavKaria  I am a gssoc-extd contributor and also hacktober contributer

**Comment by MinavKaria** [comment]
You are good to go

**Comment by MinavKaria** [comment]
Hello @laxmanp090404! Your issue #67 has been closed. Thank you for your contribution!🚀
