### ISSUE TITLE
Feature Request : Addition of Back to Top Button 

### ISSUE THREAD

**Issue by Shariq2003** [MinavKaria/Ratna-Supermarket#68]
There should be a back-to-top button on the web app so that if the user scrolls down to the bottom it can easily scroll up to top by just a single click.

**Comment by MinavKaria** [comment]
Hi @Shariq2003! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @Shariq2003! Your issue #68 has been closed. Thank you for your contribution!🚀
