### ISSUE TITLE
Form Validation Missing in SignUp Page & Cancel Button not Working in Logout Container 

### ISSUE THREAD

**Issue by Shariq2003** [MinavKaria/Ratna-Supermarket#69]
Email Validation is missing in SignUp Form

https://github.com/user-attachments/assets/a892c615-c6e8-4ee3-808f-68d37b819e19

Cancel Button not working in Logut container

https://github.com/user-attachments/assets/70e07ed7-5e8f-45c3-87e9-c232bad8f8fd

@MinavKaria please assign this to me.

**Comment by chopdepratik** [comment]
I would like to work on it. Please  assign  this issue to me ,

**Comment by chopdepratik** [comment]
I Would like to work on this issue, Please assign me this issue

**Comment by Shariq2003** [comment]
@MinavKaria please assign this to me.
