### ISSUE TITLE
Order PDF Invoice Download Feature

### ISSUE THREAD

**Issue by ParasY1724** [MinavKaria/Ratna-Supermarket#70]
**Description:**
Adding Feature that will allow user to download the generated invoice pdf of a order from My Orders Section.

**Comment by MinavKaria** [comment]
Hi @ParasY1724! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by ParasY1724** [comment]
> Hi @ParasY1724! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Ok sir , i had recently more on similar feature.

**Comment by MinavKaria** [comment]
Hello @ParasY1724! Your issue #70 has been closed. Thank you for your contribution!🚀

**Comment by MinavKaria** [comment]
Thank you for your contribution. Don't forget to star if you liked contributing to this repo.
