### ISSUE TITLE
[Bug] Fix Vendor Page (Vendor Side Form) No scroll bar

### ISSUE THREAD

**Issue by ParasY1724** [MinavKaria/Ratna-Supermarket#71]
**Description:**
At Frontend at /vendor page , vendor side form page is not scrollable.
![Peek 2024-10-06 09-37](https://github.com/user-attachments/assets/6f22065e-0df2-4585-b596-40c1a65d4a8c)

**Comment by ParasY1724** [comment]
please assign this task to me

**Comment by MinavKaria** [comment]
Hello @ParasY1724! Your issue #71 has been closed. Thank you for your contribution!🚀
