### ISSUE TITLE
Topic:improvement of UI/UX & some other detailings

### ISSUE THREAD

**Issue by Anushaburnwal** [MinavKaria/Ratna-Supermarket#77]
### Describe the types of topics you'd add in our Website

the design of the page is not looking professional make one separate sign up page. issue in delivery location the delivery location when we are adding the pin code the city name or the location came but when we dont click the location and instead we click on submit button it is not working and the size of the delivery page is not fitting properly the location name got half cut hope you understand what i am saying and one feedback section is also needed as it is the website how other users can understand whether it is an good website for marketing or not

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @Anushaburnwal! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by Anushaburnwal** [comment]
Thank you for your prompt response! I'm happy to contribute and collaborate to improve the project further.

**Comment by MinavKaria** [comment]
Hello @Anushaburnwal! Your issue #77 has been closed. Thank you for your contribution!🚀
