### ISSUE TITLE
Enhance Image Carousel Functionality 

### ISSUE THREAD

**Issue by ShivamTiwari0214** [MinavKaria/Ratna-Supermarket#78]
The image carousel currently requires a click on specific icons to change images.
![image](https://github.com/user-attachments/assets/f2cd58ef-e7ba-4f29-8371-103098c94474)
look and feel of this icon is not good, effective the U.X. 

 I propose enhancing the functionality to allow **_automatic image transitions over time_**. Additionally, change the position, size, design of the icon (similar to amazon). This will improve usability and provide a smoother experience for users.

![image](https://github.com/user-attachments/assets/c8cd5300-8a97-469e-8494-304840380a13)

@MinavKaria  please assign this issue to me, Thankyou.

**Comment by MinavKaria** [comment]
Hi @ShivamTiwari0214! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @ShivamTiwari0214! Your issue #78 has been closed. Thank you for your contribution!🚀
