### ISSUE TITLE
Fix Responsiveness of Delivery Button on Header

### ISSUE THREAD

**Issue by samar12-rad** [MinavKaria/Ratna-Supermarket#8]
The UI of the website is not fully responsive on the header. Specifically, the "Delivery" button contains elements that go out of its bounding box, affecting the clean appearance of the design. This issue becomes more noticeable on smaller screen sizes.

Proposed Solution:

Ensure that the elements within the "Delivery" button (icon and text) remain properly aligned and contained within the box.
Implement responsive CSS to adjust the size and layout of the button for different screen sizes and resolutions.
Conduct tests to verify that the header remains visually consistent across all devices (mobile, tablet, desktop).
Fixing this will improve the overall user experience by making the header more visually appealing and functional on various screen sizes.
![image](https://github.com/user-attachments/assets/74dae810-33ff-409e-b621-760ed9ca7263)

**Comment by samar12-rad** [comment]
@MinavKaria  can you assign me this issue?

**Comment by MinavKaria** [comment]
Hello @samar12-rad! Your issue #8 has been closed. Thank you for your contribution!🚀
