### ISSUE TITLE
Add Hover and Color to Social Icons

### ISSUE THREAD

**Issue by Shekhar-Raj** [MinavKaria/Ratna-Supermarket#80]
<h2>I want to add a hover effect to the social icons, so whenever i hover to icon the size of icon increases and each icon change their color to basic:
</h2>

<h3>Here:</h3>

![image](https://github.com/user-attachments/assets/cf529f28-83d6-4e96-abb6-2670bf045de2)

<h2>Demo:</h2>

https://github.com/user-attachments/assets/b58f62f6-c889-4ee3-81b7-ebf535b1fe4d

**Comment by MinavKaria** [comment]
Hi @Shekhar-Raj! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @Shekhar-Raj! Your issue #80 has been closed. Thank you for your contribution!🚀
