### ISSUE TITLE
Topic:fix responsiveness

### ISSUE THREAD

**Issue by krishpathak** [MinavKaria/Ratna-Supermarket#81]
### Describe the types of topics you'd add in our Website

The login page is not properly responsive.

Earlier login page
![image](https://github.com/user-attachments/assets/e2cf81a0-40d7-4d10-8703-f206329c6572)

The updated login page
![image](https://github.com/user-attachments/assets/3ebdb8eb-2f65-445e-80ce-02ff44616004)

I would like to fix it @MinavKaria please assign me task!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by krishpathak** [comment]
Hey @MinavKaria please let me know the issue that has been there in my last PR which had been closed by you unmerged!! So, I can fix it and make new PR.

**Comment by MinavKaria** [comment]
@krishpathak This wasn't required, If you find any other issue feel free to open a new issue.
