### ISSUE TITLE
Quantity selector for individual products

### ISSUE THREAD

**Issue by Bhum-ika** [MinavKaria/Ratna-Supermarket#83]
When clicked on a product, there is no feature of adding or reducing more quantity of same product.
I would like to work on this issue .
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by MinavKaria** [comment]
Hi @Bhum-ika! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @Bhum-ika! Your issue #83 has been closed. Thank you for your contribution!🚀
