### ISSUE TITLE
[Bug] Go back option for User Not handled properly

### ISSUE THREAD

**Issue by Akshithsaai** [MinavKaria/Ratna-Supermarket#87]
I want to work on this bug to ensure the functionality of the button. 
![image](https://github.com/user-attachments/assets/53ff2518-8cc1-4c20-8f79-a366cd24426f)

@MinavKaria Please Assign me this issue.

**Comment by Akshithsaai** [comment]
@MinavKaria please review the change

**Comment by MinavKaria** [comment]
Hello @Akshithsaai! Your issue #87 has been closed. Thank you for your contribution!🚀
