### ISSUE TITLE
Add Geolocation Feature to Capture User's Location on Visit

### ISSUE THREAD

**Issue by OmkeshwarGupta** [MinavKaria/Ratna-Supermarket#88]
### Describe the types of topics you'd add in our Website

We need to implement a geolocation feature on our e-commerce website to capture the user's location when they visit the site. The location data will be used to enhance the user experience, such as displaying location-based recommendations, default shipping addresses, and pincode.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC-24-extd contributor
- [X] Soon, I'll complete it and create a Pull Request.

**Comment by MinavKaria** [comment]
Hi @OmkeshwarGupta! Thanks for opening this issue on Ratna Supermarket. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by MinavKaria** [comment]
Hello @OmkeshwarGupta! Your issue #88 has been closed. Thank you for your contribution!🚀
