### ISSUE TITLE
Update Navbar to Display User's Name After Login instead of login Button

### ISSUE THREAD

**Issue by Mdraza78** [MinavKaria/Ratna-Supermarket#9]
Proposed Solution:
Replace the "Login" button with the user's name after login. Use conditional rendering to check the authentication status and display the user's name if they are logged in. This change will enhance user experience by providing a personalized interface.

**Comment by MinavKaria** [comment]
This is already implemented
![image](https://github.com/user-attachments/assets/c260d31f-c2f3-4741-bce8-38139ea0737e)

Are you interpreting something else ?

**Comment by Mdraza78** [comment]
Add Forgot password in Login If user Forgot

Issue:
Currently, there is no option for users to reset their password if they forget it, which can lead to frustration and hinder access to their accounts.

Proposed Solution:
Implement a "Forgot Password" link on the login page. This link should direct users to a password recovery process, where they can enter their registered email address to receive instructions for resetting their password. This enhancement will improve user accessibility and overall experience.

**Comment by Mdraza78** [comment]
ok
